# Introduction {#sec:introduction}

This stock assessment `r sp` (*`r science_name`*, also referred to as `r common_name`)

The primary data sources for this `r sp` (*`r science_name`*, also referred
to as `r common_name`) assessment include an acoustic survey, fishery
catch, mean weight-at-age data, maturity-at-age data, as well as survey
and fishery age-composition data. The assessment depends primarily upon an
index of biomass from the acoustic survey for information on the scale of the
current population. Age-composition data provide additional information
allowing the model to resolve strong and weak cohorts. The catch is an
important source of information regarding changes in abundance and places a
lower bound on the available population biomass in each year.

This assessment is fully Bayesian, with the base model incorporating prior
information on several key parameters (including informative priors
on natural mortality, $M$, and steepness of the stock--recruitment relationship,
$h$) and integrating over parameter uncertainty to provide results that can be
probabilistically interpreted. From a range of alternate models investigated,
a subset of sensitivity analyses are also reported to provide a
broad qualitative comparison of structural uncertainty with respect to the
base model (Section~\@ref(sec:assessment-sensitivity-analyses)). The model is implemented using
version `r ss_version` of the Stock Synthesis software [@MethotWetzel2013].
The `r assess_yr` base model is structurally similar to the offshore stock assessment model,
except this base model does not include estimates of annual
recruitment deviations in the final two years of the model
All model runs reported in this document are performed in a Bayesian
context.

## Stock structure and life history {#sec:intro-stock-structure}

`r sp` is a semi-pelagic, schooling species distributed along the west coast of
North America, generally ranging in latitude from 25° to 55° North Latitude (N.~Lat.);
Figure~\@ref(fig:main-overview-map-fig). It is among 18 species of `r sp` from
four genera (being the majority of the family *Merluccidae*), which are found
in both hemispheres of the Atlantic and Pacific Oceans [@AlheitPitcher1995;
@LlorisMatallanasEtAl2005]. The coastal population of `r sp` is currently the
most abundant groundfish population in the California Current system. Smaller
populations of this species occur in the major inlets of the Northeast Pacific
Ocean, including the Strait of Georgia, the Puget Sound, and the Gulf of
California. Each of these smaller populations are genetically distinct from the
coastal population [@VroomanPaloma1977; @IwamotoFordEtAl2004;
@KingMcFarlaneEtAl2012; @GarciaEtAl2018; @LongoEtAl2024]. The coastal
population is also distinguished from the inshore populations by larger size at
age and seasonal migratory behavior and from fish off the west coast of Baja
California by smaller size at age and later spawning [@Zamora-Garcia2020].

The coastal population of `r sp` typically ranges from the waters off southern
California to northern British Columbia and rarely into southern Alaska, with
the northern boundary related to fluctuations in annual migration
[@HamelEtAl2015] depending, in part, on water temperature
[@MalickHunsickerEtAl2020; @MalickSiedleckiEtAl2020]. In spring, adult
`r sp` migrate onshore and northward to feed along the continental shelf and
slope from Northern California to Vancouver Island. In summer, `r sp` often
form extensive mid-water aggregations in association with the continental
shelf break, with the highest densities located over bottom depths of
200--300~m [@DornMethot1991; @DornMethot1992].

Older `r sp` exhibit the greatest northern migration each season, with two-
and three-year old fish rarely being observed in Canadian waters north of Southern
Vancouver Island. During El Niño events (warm ocean conditions such as in
1998 and 2016), a larger proportion of the population migrates into Canadian
waters (Figure~\@ref(fig:main-acoustic-age2-bs-fig)), due to temperature effects
[@MalickHunsickerEtAl2020] and possibly intensified northward transport
during the period of active migration [@Dorn1995b; @AgostiniFrancisEtAl2006].
In contrast, La Niña conditions (colder water, such as in 2001, 2011, and
2021) result in a southward shift in the distribution of `r sp`, with a much
smaller proportion of the population found in Canadian waters compared to
during El Niño years, a trend evident from the acoustic surveys
(Figure~\@ref(fig:main-acoustic-age2-bs-fig)). In general, warmer than average
thermal habitat conditions for mature `r sp` lead to relatively higher biomass
further north and relatively lower biomass around the U.S.--Canadian border,
while cooler than average conditions lead to relatively higher biomass of
immature `r sp` generally spread evenly across their distribution
[@MalickHunsickerEtAl2020]. The distribution of age-1 fish also changes between
years (Figure~\@ref(fig:main-acoustic-age1-bs-fig)).

## Ecosystem considerations {#sec:intro-ecosystem-considerations}

`r sp` are important to ecosystem dynamics in the Eastern Pacific Ocean due
to their relatively large total biomass and potentially large role as both prey
and predator [@JTC2013]. Ongoing research investigating abiotic (i.e.,
environmental conditions) and biotic (e.g., maturity and diet) drivers of the
distribution, recruitment, growth, and survival of `r sp` could provide
insight into how the population is linked with broader ecosystem
considerations. For example, @TurleyRykaczewski2019 found decreased
survival of larval `r sp` as storm events increased, contrary to many other
species in the Southern California Current Ecosystem. An analysis of drivers of
recruitment across the maternal preconditioning, egg, and larval phases of
`r sp` recruitment indicated recruitment is associated with eddy kinetic
energy, the location of the North Pacific Current bifurcation, and upwelling
during maternal preconditioning, as well as with northward long-shore transport
and the number of days between storm events during larval stages
[@VestfalsEtAl2023]. @Phillips2022 suggest temperature
dynamically influences the co-occurrence of `r sp` and krill (i.e.,
euphausiids; *Euphausiacea*), which can influence annual `r sp` growth
and recruitment as the availability of key prey species shifts. Temperature
was also found to impact the co-occurrence of `r sp` and Shortbelly Rockfish
(*Sebastes jordani*, Sebastidae) during the 2014--2016 marine heatwave
[@FreeEtAl2023]. An index of abundance for Humboldt Squid (*Dosidicus
gigas*) suggests that the abundance of `r sp` decreases with increasing squid
abundance [@StewartHazenEtAl2014; @JTC2015]. Many additional research topics
relevant to `r sp` distribution, recruitment, and growth patterns in relation
to oceanographic conditions have been investigated [@ResslerHolmesEtAl2007;
@HamelEtAl2015; @MalickHunsickerEtAl2020; @MalickSiedleckiEtAl2020] and provide
a foundation for further research on these topics.

Motivated by such research, focusing on @VestfalsEtAl2023 in particular, we
include a new Pacific Hake-specific ecosystem summary
in Appendix~\@ref(sec:app-ecosystem-report). We collate time series of relevant ecosystem
processes that are believed to influence `r sp` recruitment. These include prey/competitors (Pacific Herring, \emph{Clupea pallasii}, off
Vancouver Island) and predators (age-1 `r sp`), basin-scale oceanography, and
local calculations of sea-surface temperature, alongshore transport, sea-surface
height, mixed layer depths, and the strength of poleward undercurrent. These are
calculated for specific areas and time periods corresponding to different
life-history stages of `r sp` [@VestfalsEtAl2023]. While not
comprehensive or definitive, this is a start to including such Pacific Hake-relevant
ecosystem information in the annual stock assessment.

Recent oceanographic trends and large-scale ecosystem conditions,
as summarized in the National Oceanic and Atmospheric Administration’s (NOAA)
annual [California Current Ecosystem Status Reports](https://www.pcouncil.org/annual-california-current-ecosystem-status-report/)
(Leising et al. in prep, for 2024)
provide insight into potential drivers of `r sp` population dynamics and fleet
operations. Periods of high productivity are often marked by strong winter
and spring upwelling which brings nutrients to coastal waters, cooler temperatures, an
energy-rich copepod community, and high productivity of krill, a key food source for `r sp`
[@BuckleyLivingston1997; @CCIEA2021].

During 2024 (Leising et al. in prep), basin-scale climate patterns suggest below average to
average conditions in the California Current Ecosystem (CCE). A strong El Niño
in 2023-24 resulted in warm temperatures during winter and spring and delayed
upwelling. The responses of lower trophic level communities to these conditions
were typical of those observed during previous El Niño events. For example, the
biomass of lipid-rich northern copepods and adult krill were below average in
the northern region of the CCE in winter and spring. However, the El Niño
conditions dissipated quickly and the ecosystem transitioned to cooler and more
productive conditions following a strong spring upwelling. The northern copepods
and krill recovered to near average abundances in summer and fall, and the
forage community throughout the CCE was relatively diverse and
productive. Observations of forage communities in the central and southern
regions of the CCE indicate that the abundances of larval and juvenile `r sp` in
these regions are above average and have been increasing over the past five
years. At the same time, consumption of `r sp` by Bluefin Tuna and
Swordfish has been well above average in recent years (2022-23) and the spawning
stock biomass of these predators has been increasing over this same period as
well. See Appendix~\@ref(sec:app-ecosystem-report) for more details and a
'risk table' documenting ecosystem and climate factors potentially affecting `r sp`
stock productivity and uncertainty.

Using empirical weight-at-age data in the model allows for
time-varying growth without needing a mechanistic relationship or environmental
data, which facilitates an `Ecosystem Approach to Fisheries Management'
(a priority for Department of Fisheries and Oceans [DFO] and NOAA; see Section~\@ref(sec:data-weight-at-age)).
Furthermore, the year-specific maturity-at-age specifically includes a
temperature effect from a spatiotemporal model (Section~\@ref(sec:data-maturity)).
Related ongoing research should provide more insights into the specific mechanisms
affecting changes in growth and fecundity, which will enable further condition-specific prediction
capabilities (e.g., assumptions of growth, or weight at age, and fecundity during forecast
years). It is hypothesized that temporal changes in weight-at-age data may be
due to ecosystem effects such as prey availability, predator abundance, and
ocean temperature [@ChittaroGrandinetal2022].

## Management of `r sp` {#sec:intro-management}

More here...
