#' Load and filter by area and gear type the commercial sample data
#'
#' @description
#' Load the commercial sample data from an RDS file generated by
#' [extract_samples_from_db()]. The filename is stored in the package
#' data variable [sample_data_rds_fn]
#'
#' @details
#' The following filtering is performed in this function for all fleets:
#' 1) Areas - Area 4B (Strait of Georgia) with area 12 (North Vancouver Island)
#'    and 20 (Strait of Juan de Fuca) removed
#' 2) Fishing gear - Midwater trawl only by default
#'
#' @param fn The file name for the sample RDS file
#' @param gear_type A vector of fishing gear type (description). Must be
#' one or more of: `midwater trawl`, `bottom trawl`, `shrimp trawl`,
#' or `unknown trawl`. If `NULL`, all type will be included
#'
#' @return A data frame containing filtered Canadian samples
#' @export
load_sample_data <- function(

    fn = file.path("/srv/hake-sog/other/samples/hake-sog-2025-commercial-samples.rds"),
    gear_type = "midwater trawl"){

  if(!file.exists(fn)){
    stop("The file:\n`", fn, "`\ndoes not exist. Run ",
         "`canada_extract_sample_data()` to create it")
  }

  out <- readRDS(fn) |>
    dplyr::filter(major_stat_area_code %in% c("01", "02") &
                    !minor_stat_area_code %in% c("12", "20"))

  if(!is.null(gear_type)){
    gear_type <- toupper(gear_type)
    gear_pat <- paste(gear_type, collapse = "|")

    out <- out %>%
      dplyr::filter(grepl(gear_pat, .$gear_desc))
  }

  out
}
